export const GET_ALL_CHAT_USERS_REQUEST="GET_ALL_CHAT_USERS_REQUEST";
export const GET_ALL_CHAT_USERS_SUCCESS="GET_ALL_CHAT_USERS_SUCCESS";
export const GET_ALL_CHAT_USERS_FAILURE="GET_ALL_CHAT_USERS_FAILURE";

export const SEND_MESSAGE_REQUEST="SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS="SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE="SEND_MESSAGE_FAILURE"

export const GET_MESSAGES_REQUEST="GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS="GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILURE="GET_MESSAGES_FAILURE";

export const SET_MESSAGES="SET_MESSAGES"
