export const LOGIN_DETAILS_REQUEST = "LOGIN_DETAILS_REQUEST"; 
export const LOGIN_DETAILS_SUCCESS = "LOGIN_DETAILS_SUCCESS";
export const LOGIN_DETAILS_SUCCESS_FAILURE = "LOGIN_DETAILS_SUCCESS_FAILURE";
export const LOGIN_DETAILS_FAILURE = "LOGIN_DETAILS_FAILURE";

export const SIGNUP_DETAILS_REQUEST = "SIGNUP_DETAILS_REQUEST";
export const SIGNUP_DETAILS_SUCCESS = "SIGNUP_DETAILS_SUCCESS";
export const SIGNUP_DETAILS_FAILURE = "SIGNUP_DETAILS_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";